apiVersion: apps/v1
kind: Deployment
metadata:
  name: beginner-html-site
spec:
  replicas: 5
  selector:
    matchLabels:
      app: beginner-html-site
  template:
    metadata:
      labels:
        app: beginner-html-site
    spec:
      containers:
        - name: web
          image: vasudevad/beginner-html-site:latest
          ports:
            - containerPort: 80
